import { Button, GridBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    always-on-top: true;
    title: "Tibia Timer";
    in-out property <int> curr-timer-value;
    callback start-timer(string, string, string);
    GridBox {
        Row {
            Text { text: "Critical alarm after:"; }
            critical-threshold := LineEdit {
                input-type: number;
                placeholder-text: "[seconds]";
            }
        }
        Row {
            Text { text: "Warning alarm after:"; }
            warning-threshold := LineEdit {
                input-type: number;
                placeholder-text: "[seconds]";
            }
        }
        Row {
            Text { text: "Total time:"; }
            total-time := LineEdit {
                input-type: number;
                placeholder-text: "[seconds]";
            }
        }
        Row {
            Button {
                text: "Start Timer";
                clicked => {
                    root.start-timer(total_time.text, warning-threshold.text, critical-threshold.text);
                    self.text = "Timer running...";
                }
            }
            Text { text: "\{root.curr-timer-value}"; }
        }
        Row {
            Text {
                font-size: 10px;
                text: "Copyright (c) 2024 Maras";
            }
        }
    }
}